### ISSUE TITLE
Состояние завершенности курса

### ISSUE THREAD

**Issue by d4got10** [Quatters/platform-for-online-internships#38]
Добавить в сущность курса пользователя дату завершения.
Курс завершается, когда завершены все тесты? Возникает проблема с попытками, если не все попытки потрачены, то курс не должен завершиться. Может ввести кнопку завершения?
По завершению курса все его компетенции зачисляются стажёру

**Comment by Quatters** [comment]
@d4got10 а как насчет такой идеи? У нас в курсе пользователя есть прогресс (пока нигде не сеттается). Будем его обновлять с каждой законченной попыткой теста как сумму тестов с максимальным баллом, набранным стажером, деленную на максимально возможное количество баллов за весь курс. В курс добавим поле "проходной балл", измеряемый в процентах, который можно будет указать админу при создании. Если в момент очередного пересчета прогресса курса пользователя балл становится больше проходного, то считаем курс завершенным и начисляем стажеру компетенции. Т.е. критерием завершенности у нас будет балл пользователя > проходной балл. На фронте я могу даже показать модалку в этот момент с сообщением типа "вы набрали достаточно баллов, вот вам компетенции и т.п.".

**Comment by Quatters** [comment]
Идею выше я озвучивал Крестниковой, она без возражений
